export const siteConfig = {
  name: "Chowra Logistics and Couriers Limited",
  shortName: "Chowra Logistics",
  tagline: "Whatever You Order. We Deliver.",
  description:
    "Chowra Logistics and Couriers Limited provides modern courier, express delivery, freight, e-commerce and logistics solutions across cities and borders.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://www.chowralogistics.com",
  keywords: [
    "logistics company",
    "courier services",
    "express delivery",
    "freight and cargo",
    "e-commerce logistics",
    "domestic courier India",
    "international courier",
    "corporate logistics",
    "door to door delivery",
    "shipment tracking",
  ],
  contact: {
    phone: "+91 000 000 0000",
    email: "support@chowralogistics.com",
    address: "Visakhapatnam, Andhra Pradesh, India",
    hours: "Mon – Sat, 9:00 AM – 7:00 PM IST",
  },
  social: {
    twitter: "https://twitter.com/chowralogistics",
    linkedin: "https://linkedin.com/company/chowralogistics",
    instagram: "https://instagram.com/chowralogistics",
    facebook: "https://facebook.com/chowralogistics",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "Services", href: "/services" },
    { label: "Tracking", href: "/tracking" },
    { label: "Coverage", href: "/#coverage" },
    { label: "About", href: "/#why-chowra" },
    { label: "Contact", href: "/contact" },
  ],
  footerColumns: [
    {
      title: "Company",
      links: [
        { label: "About", href: "/#why-chowra" },
        { label: "Services", href: "/services" },
        { label: "Coverage", href: "/#coverage" },
        { label: "Contact", href: "/contact" },
      ],
    },
    {
      title: "Services",
      links: [
        { label: "Domestic", href: "/services/domestic" },
        { label: "International", href: "/services/international" },
        { label: "Express", href: "/services/express" },
        { label: "E-commerce", href: "/services/ecommerce" },
        { label: "Freight", href: "/services/freight" },
        { label: "Corporate", href: "/services/corporate" },
      ],
    },
    {
      title: "Support",
      links: [
        { label: "Track Shipment", href: "/tracking" },
        { label: "Get a Quote", href: "/quote" },
        { label: "Contact", href: "/contact" },
        { label: "FAQ", href: "/contact#faq" },
      ],
    },
  ],
  services: [
    {
      slug: "domestic",
      title: "Domestic Courier",
      short: "Fast and reliable delivery across India.",
      description:
        "Pan-India pickup and delivery built on a dependable hub-and-spoke network, engineered for speed without compromising on care.",
      image: "domestic",
      href: "/services/domestic",
      features: [
        "Pickup from home, office or warehouse",
        "City-to-city and intra-state delivery",
        "Real-time status updates on every shipment",
      ],
    },
    {
      slug: "international",
      title: "International Courier",
      short: "Cross-border delivery with reliable handling.",
      description:
        "Door-to-door international shipping with customs documentation support and dependable transit visibility across major trade lanes.",
      image: "international",
      href: "/services/international",
      features: [
        "Customs documentation assistance",
        "Coverage across major global trade lanes",
        "Careful handling for cross-border shipments",
      ],
    },
    {
      slug: "express",
      title: "Express Delivery",
      short: "Priority shipping for time-sensitive packages.",
      description:
        "When timing matters most, our express network prioritises your shipment from pickup to final mile.",
      image: "express",
      href: "/services/express",
      features: [
        "Priority handling at every hub",
        "Faster pickup-to-delivery turnaround",
        "Ideal for urgent documents and parcels",
      ],
    },
    {
      slug: "ecommerce",
      title: "E-commerce Logistics",
      short: "Scalable fulfilment and last-mile delivery.",
      description:
        "End-to-end fulfilment for online sellers — warehousing, order packing, last-mile delivery and returns handling.",
      image: "ecommerce",
      href: "/services/ecommerce",
      features: [
        "Warehousing and order fulfilment",
        "Last-mile delivery for online orders",
        "Returns and reverse-logistics handling",
      ],
    },
    {
      slug: "freight",
      title: "Freight & Cargo",
      short: "Reliable transportation for larger shipments.",
      description:
        "Full-load and part-load freight solutions for heavier, bulkier shipments moving between cities and hubs.",
      image: "freight",
      href: "/services/freight",
      features: [
        "Full-load and part-load options",
        "Suited for bulk and heavy shipments",
        "Scheduled inter-city freight movement",
      ],
    },
    {
      slug: "corporate",
      title: "Corporate Logistics",
      short: "Customized logistics solutions for businesses.",
      description:
        "Dedicated logistics programs tailored to a business's shipping volume, schedule and supply-chain requirements.",
      image: "corporate",
      href: "/services/corporate",
      features: [
        "Tailored logistics programs for businesses",
        "Support for recurring shipping schedules",
        "Dedicated account coordination",
      ],
    },
  ],
  cityOptions: {
    andhraPradesh: [
      "Visakhapatnam",
      "Vijayawada",
      "Guntur",
      "Tirupati",
      "Kakinada",
      "Rajahmundry",
      "Nellore",
      "Anantapur",
      "Kurnool",
      "Kadapa",
      "Srikakulam",
      "Vizianagaram",
      "Eluru",
      "Ongole",
      "Machilipatnam",
    ],
    india: [
      "Hyderabad",
      "Bengaluru",
      "Chennai",
      "Mumbai",
      "Pune",
      "New Delhi",
      "Kolkata",
      "Ahmedabad",
      "Jaipur",
      "Lucknow",
      "Bhubaneswar",
      "Kochi",
      "Coimbatore",
      "Indore",
      "Nagpur",
      "Surat",
      "Guwahati",
      "Patna",
      "Visakhapatnam",
    ],
  },
  coverageCities: [
    "Visakhapatnam",
    "Hyderabad",
    "Bengaluru",
    "Chennai",
    "Mumbai",
    "Delhi",
    "Dubai",
    "Singapore",
    "London",
  ],
  stats: [
    { value: "100+", label: "Service Locations" },
    { value: "24/7", label: "Shipment Visibility" },
    { value: "99%", label: "Delivery Reliability*" },
    { value: "Pan-India", label: "Coverage" },
  ],
  statsDisclaimer:
    "*Sample figures shown for illustration. Contact us for current service metrics.",
} as const;

export type ServiceItem = (typeof siteConfig.services)[number];
